
package main.java.group4.week39.gdp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GDPService", targetNamespace = "http://ws.demo1.ties532.jyu.fi/", wsdlLocation = "http://ub1.ad.jyu.fi/GDP?wsdl")
public class GDPService
    extends Service
{

    private final static URL GDPSERVICE_WSDL_LOCATION;
    private final static WebServiceException GDPSERVICE_EXCEPTION;
    private final static QName GDPSERVICE_QNAME = new QName("http://ws.demo1.ties532.jyu.fi/", "GDPService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ub1.ad.jyu.fi/GDP?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GDPSERVICE_WSDL_LOCATION = url;
        GDPSERVICE_EXCEPTION = e;
    }

    public GDPService() {
        super(__getWsdlLocation(), GDPSERVICE_QNAME);
    }

    public GDPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GDPSERVICE_QNAME, features);
    }

    public GDPService(URL wsdlLocation) {
        super(wsdlLocation, GDPSERVICE_QNAME);
    }

    public GDPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GDPSERVICE_QNAME, features);
    }

    public GDPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GDPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GDP
     */
    @WebEndpoint(name = "GDPPort")
    public GDP getGDPPort() {
        return super.getPort(new QName("http://ws.demo1.ties532.jyu.fi/", "GDPPort"), GDP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GDP
     */
    @WebEndpoint(name = "GDPPort")
    public GDP getGDPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.demo1.ties532.jyu.fi/", "GDPPort"), GDP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GDPSERVICE_EXCEPTION!= null) {
            throw GDPSERVICE_EXCEPTION;
        }
        return GDPSERVICE_WSDL_LOCATION;
    }

}
