CREATE TABLE DEPT_LOCATIONS(
  Dnumber INT,
  Dlocation VARCHAR(15),
  PRIMARY KEY (Dnumber, Dlocation)
);

CREATE TABLE PROJECT(
  Pname VARCHAR(15) NOT NULL,
  Pnumber INT NOT NULL,
  Plocation VARCHAR(15),
  Dnum INT NOT NULL,
  PRIMARY KEY(Pnumber),
  UNIQUE (Pname)
);

CREATE TABLE WORKS_ON(
  Essn CHAR(9) NOT NULL,
  Pno INT NOT NULL,
  Hours DECIMAL(3,1) NOT NULL,
  PRIMARY KEY (Essn, Pno)
);

CREATE TABLE DEPENDENT(
  Essn CHAR(9) NOT NULL,
  Dependent_name VARCHAR(15) NOT NULL,
  Sex CHAR,
  Bdate DATE,
  Relationship VARCHAR(8),
  PRIMARY KEY (Essn, Dependent_name)
);

CREATE TABLE EMPLOYEE(
  Dno INT NOT NULL DEFAULT 1,
  Fname VARCHAR(15),
  Minit CHAR(1),
  Lname VARCHAR(15),
  Ssn CHAR(9) NOT NULL,
  Bdate DATE,
  Address VARCHAR(30),
  Sex CHAR(1),
  Salary INT,
  Super_ssn CHAR(9),
  CONSTRAINT EMPPK 
    PRIMARY KEY (Ssn)
);

CREATE TABLE DEPARTMENT(
  Mgr_ssn CHAR(9) NOT NULL DEFAULT '888665555',
  Dname VARCHAR(15),
  Dnumber INT,
  Mgr_start_date DATE,
  CONSTRAINT DEPTPK
    PRIMARY KEY(Dnumber),
  CONSTRAINT DEPTSK
    UNIQUE(Dname)
);

ALTER TABLE DEPT_LOCATIONS  
ADD FOREIGN KEY (Dnumber) REFERENCES DEPARTMENT(Dnumber)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE DEPT_LOCATIONS
ADD FOREIGN KEY (Dnumber) REFERENCES DEPARTMENT(Dnumber);

ALTER TABLE PROJECT
ADD FOREIGN KEY (Dnum) REFERENCES DEPARTMENT(Dnumber);

ALTER TABLE WORKS_ON
ADD FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn);

ALTER TABLE WORKS_ON
ADD FOREIGN KEY (Pno) REFERENCES PROJECT(Pnumber);

ALTER TABLE DEPENDENT
ADD FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT EMPDEPTFK
FOREIGN KEY(Dno) REFERENCES DEPARTMENT(Dnumber)
ON DELETE SET DEFAULT ON UPDATE CASCADE	;

ALTER TABLE DEPARTMENT
ADD CONSTRAINT DEPTMGRFK
FOREIGN KEY (Mgr_ssn) REFERENCES EMPLOYEE(Ssn)
ON DELETE SET DEFAULT ON UPDATE CASCADE;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT EMPSUPERRFK 
FOREIGN KEY (Super_ssn) REFERENCES EMPLOYEE(Ssn)
ON DELETE SET NULL ON UPDATE CASCADE;