
package fi.jyu.ties456.group4.week40.gdp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GDP", targetNamespace = "http://ws.demo1.ties532.jyu.fi/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GDP {


    /**
     * 
     * @param countryCode
     * @return
     *     returns java.lang.Double
     * @throws NoSuchCountryException_Exception
     */
    @WebMethod
    @WebResult(name = "GDP", targetNamespace = "")
    @RequestWrapper(localName = "getGDP", targetNamespace = "http://ws.demo1.ties532.jyu.fi/", className = "fi.jyu.ties456.group4.week40.gdp.GetGDP")
    @ResponseWrapper(localName = "getGDPResponse", targetNamespace = "http://ws.demo1.ties532.jyu.fi/", className = "fi.jyu.ties456.group4.week40.gdp.GetGDPResponse")
    public Double getGDP(
        @WebParam(name = "countryCode", targetNamespace = "")
        String countryCode)
        throws NoSuchCountryException_Exception
    ;

}
