
package fi.jyu.it.ties456.week38.services.courses;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentISService", targetNamespace = "http://ws.demo1.ties532.jyu.fi/", wsdlLocation = "http://ub1.ad.jyu.fi/courses?wsdl")
public class StudentISService
    extends Service
{

    private final static URL STUDENTISSERVICE_WSDL_LOCATION;
    private final static WebServiceException STUDENTISSERVICE_EXCEPTION;
    private final static QName STUDENTISSERVICE_QNAME = new QName("http://ws.demo1.ties532.jyu.fi/", "StudentISService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ub1.ad.jyu.fi/courses?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTISSERVICE_WSDL_LOCATION = url;
        STUDENTISSERVICE_EXCEPTION = e;
    }

    public StudentISService() {
        super(__getWsdlLocation(), STUDENTISSERVICE_QNAME);
    }

    public StudentISService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTISSERVICE_QNAME, features);
    }

    public StudentISService(URL wsdlLocation) {
        super(wsdlLocation, STUDENTISSERVICE_QNAME);
    }

    public StudentISService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTISSERVICE_QNAME, features);
    }

    public StudentISService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentISService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentIS
     */
    @WebEndpoint(name = "StudentISPort")
    public StudentIS getStudentISPort() {
        return super.getPort(new QName("http://ws.demo1.ties532.jyu.fi/", "StudentISPort"), StudentIS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentIS
     */
    @WebEndpoint(name = "StudentISPort")
    public StudentIS getStudentISPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.demo1.ties532.jyu.fi/", "StudentISPort"), StudentIS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTISSERVICE_EXCEPTION!= null) {
            throw STUDENTISSERVICE_EXCEPTION;
        }
        return STUDENTISSERVICE_WSDL_LOCATION;
    }

}
